"""Station definitions for the eHYD integration."""

RIVER_STATIONS: list[dict[str, int | str]] = [
    {
        "suffix": "platzl",
        "hzbnr": 206763,
        "name": "Platzl",
        "water": "Laussabach",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "lienz_peggetz",
        "hzbnr": 212316,
        "name": "Lienz-Peggetz",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "nickelsdorf",
        "hzbnr": 210013,
        "name": "Nickelsdorf",
        "water": "Leitha",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "piringsdorf",
        "hzbnr": 210039,
        "name": "Piringsdorf",
        "water": "Rabnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "oberpullendorf",
        "hzbnr": 210062,
        "name": "Oberpullendorf",
        "water": "Stoob",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schutzen_am_gebirge",
        "hzbnr": 210096,
        "name": "Schützen am Gebirge",
        "water": "Wulka",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "morbisch_am_see",
        "hzbnr": 210120,
        "name": "Mörbisch am See",
        "water": "Neusiedler See",
        "parameter": "W",
        "unit": "m ü.A",
    },
    {
        "suffix": "neusiedl_am_see_seebad",
        "hzbnr": 210146,
        "name": "Neusiedl am See (Seebad)",
        "water": "Neusiedler See",
        "parameter": "W",
        "unit": "m ü.A",
    },
    {
        "suffix": "podersdorf_am_see_badebucht",
        "hzbnr": 210153,
        "name": "Podersdorf am See (Badebucht)",
        "water": "Neusiedler See",
        "parameter": "W",
        "unit": "m ü.A",
    },
    {
        "suffix": "markt_allhau",
        "hzbnr": 210203,
        "name": "Markt Allhau",
        "water": "Stögersbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "dobersdorf",
        "hzbnr": 210211,
        "name": "Dobersdorf",
        "water": "Lafnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "oberwart",
        "hzbnr": 210229,
        "name": "Oberwart",
        "water": "Pinka",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "woppendorf",
        "hzbnr": 210237,
        "name": "Woppendorf",
        "water": "Pinka",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "heiligenbrunn",
        "hzbnr": 210294,
        "name": "Heiligenbrunn",
        "water": "Strem",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rattersdorf",
        "hzbnr": 210310,
        "name": "Rattersdorf",
        "water": "Güns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "eltendorf",
        "hzbnr": 210401,
        "name": "Eltendorf",
        "water": "Lafnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "pinkafeld",
        "hzbnr": 210419,
        "name": "Pinkafeld",
        "water": "Pinka",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "neumarkt",
        "hzbnr": 210468,
        "name": "Neumarkt",
        "water": "Raab",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rauchwart",
        "hzbnr": 210484,
        "name": "Rauchwart",
        "water": "Strem",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lutzmannsburg",
        "hzbnr": 210500,
        "name": "Lutzmannsburg",
        "water": "Rabnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "siget_in_der_wart",
        "hzbnr": 215012,
        "name": "Siget in der Wart",
        "water": "Zickenbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "moschendorf",
        "hzbnr": 215038,
        "name": "Moschendorf",
        "water": "Pinka",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "heiligenkreuz",
        "hzbnr": 215046,
        "name": "Heiligenkreuz",
        "water": "Lafnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "oberdrauburg_ort",
        "hzbnr": 212324,
        "name": "Oberdrauburg-Ort",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "sachsenburg_sud",
        "hzbnr": 212357,
        "name": "Sachsenburg-Süd",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kolbnitz_verbund",
        "hzbnr": 212399,
        "name": "Kolbnitz-Verbund",
        "water": "Möll",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mollbrucke",
        "hzbnr": 212407,
        "name": "Möllbrücke",
        "water": "Möll",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gmund_ort",
        "hzbnr": 212431,
        "name": "Gmünd-Ort",
        "water": "Lieser",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "sandriesen",
        "hzbnr": 212498,
        "name": "Sandriesen",
        "water": "Malta",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "millstatt_see",
        "hzbnr": 212514,
        "name": "Millstatt-See",
        "water": "Millstätter See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "spittal_fasan",
        "hzbnr": 212530,
        "name": "Spittal - Fasan",
        "water": "Lieser",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "techendorf_see",
        "hzbnr": 212563,
        "name": "Techendorf-See",
        "water": "Weissensee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "mauthen",
        "hzbnr": 212647,
        "name": "Mauthen",
        "water": "Gail",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "presseggen_see",
        "hzbnr": 212746,
        "name": "Presseggen-See",
        "water": "Pressegger See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "notsch",
        "hzbnr": 212753,
        "name": "Nötsch",
        "water": "Gail",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "thorl",
        "hzbnr": 212761,
        "name": "Thörl",
        "water": "Gailitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "federaun",
        "hzbnr": 212787,
        "name": "Federaun",
        "water": "Gail",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "faak_bundessportheim_see",
        "hzbnr": 212795,
        "name": "Faak Bundessportheim-See",
        "water": "Faaker See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "miklauzhof",
        "hzbnr": 212852,
        "name": "Miklauzhof",
        "water": "Vellach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "maitratten_gnesau",
        "hzbnr": 212860,
        "name": "Maitratten-Gnesau",
        "water": "Gurk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "weitensfeld_ost",
        "hzbnr": 212886,
        "name": "Weitensfeld-Ost",
        "water": "Gurk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "portschach_see",
        "hzbnr": 212985,
        "name": "Pörtschach-See",
        "water": "Wörther See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "gumisch",
        "hzbnr": 213041,
        "name": "Gumisch",
        "water": "Gurk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "krottendorf",
        "hzbnr": 213090,
        "name": "Krottendorf",
        "water": "Lavant",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "flattach",
        "hzbnr": 213124,
        "name": "Flattach",
        "water": "Möll",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "launsdorf",
        "hzbnr": 213157,
        "name": "Launsdorf",
        "water": "Gurk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lavamund_ort",
        "hzbnr": 213173,
        "name": "Lavamünd Ort",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "amlach",
        "hzbnr": 213215,
        "name": "Amlach",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_andra_see",
        "hzbnr": 213272,
        "name": "St. Andrä-See",
        "water": "Ossiacher See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "fischering",
        "hzbnr": 213371,
        "name": "Fischering",
        "water": "Lavant",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "molbling",
        "hzbnr": 213397,
        "name": "Mölbling",
        "water": "Gurk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lavamund_grenze",
        "hzbnr": 213595,
        "name": "Lavamünd Grenze",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_veit",
        "hzbnr": 213827,
        "name": "St. Veit",
        "water": "Glan",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "klagenfurt_professor_deutschgasse",
        "hzbnr": 213934,
        "name": "Klagenfurt-Professor Deutschgasse",
        "water": "Glan",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wolfsberg_rathausplatz",
        "hzbnr": 217240,
        "name": "Wolfsberg-Rathausplatz",
        "water": "Lavant",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "opponitz_mirenau",
        "hzbnr": 207654,
        "name": "Opponitz (Mirenau)",
        "water": "Ybbs",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "greimpersdorf",
        "hzbnr": 207688,
        "name": "Greimpersdorf",
        "water": "Ybbs",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "krenstetten",
        "hzbnr": 207696,
        "name": "Krenstetten",
        "water": "Urlbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "niederndorf",
        "hzbnr": 207803,
        "name": "Niederndorf",
        "water": "Erlauf",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "weitenegg",
        "hzbnr": 207811,
        "name": "Weitenegg",
        "water": "Weitenbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "matzleinsdorf",
        "hzbnr": 207837,
        "name": "Matzleinsdorf",
        "water": "Melk",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hofstetten_bad",
        "hzbnr": 207852,
        "name": "Hofstetten (Bad)",
        "water": "Pielach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "imbach",
        "hzbnr": 207878,
        "name": "Imbach",
        "water": "Krems",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lilienfeld",
        "hzbnr": 207894,
        "name": "Lilienfeld",
        "water": "Traisen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "windpassing",
        "hzbnr": 207910,
        "name": "Windpassing",
        "water": "Traisen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "zwettl_bahnbrucke",
        "hzbnr": 207944,
        "name": "Zwettl (Bahnbrücke)",
        "water": "Kamp",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "neustift",
        "hzbnr": 207951,
        "name": "Neustift",
        "water": "Großer Kamp",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "stiefern",
        "hzbnr": 207993,
        "name": "Stiefern",
        "water": "Kamp",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "atzenbrugg_bundesstrasse",
        "hzbnr": 208009,
        "name": "Atzenbrugg (Bundesstrasse)",
        "water": "Perschling",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "siegersdorf",
        "hzbnr": 208017,
        "name": "Siegersdorf",
        "water": "Gr. Tulln",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hollenstein",
        "hzbnr": 208041,
        "name": "Hollenstein",
        "water": "Schmida",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "obermallebarn",
        "hzbnr": 208058,
        "name": "Obermallebarn",
        "water": "Göllersbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "cholerakapelle",
        "hzbnr": 208090,
        "name": "Cholerakapelle",
        "water": "Schwechat",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "fahrafeld",
        "hzbnr": 208116,
        "name": "Fahrafeld",
        "water": "Triesting",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hirtenberg",
        "hzbnr": 208124,
        "name": "Hirtenberg",
        "water": "Triesting",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schwechat_hallenbad",
        "hzbnr": 208157,
        "name": "Schwechat (Hallenbad)",
        "water": "Schwechat",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gutenstein_kirche",
        "hzbnr": 208272,
        "name": "Gutenstein (Kirche)",
        "water": "Piesting",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wollersdorf_hydro",
        "hzbnr": 208280,
        "name": "Wöllersdorf (Hydro)",
        "water": "Piesting",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "raabs_an_der_thaya",
        "hzbnr": 208629,
        "name": "Raabs an der Thaya",
        "water": "Thaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "singerin_hoellental",
        "hzbnr": 208702,
        "name": "Singerin (Hoellental)",
        "water": "Schwarza",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gloggnitz_adlerbrucke",
        "hzbnr": 208710,
        "name": "Gloggnitz (Adlerbrücke)",
        "water": "Schwarza",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "stixenstein_schlo",
        "hzbnr": 208736,
        "name": "Stixenstein (Schloß)",
        "water": "Sierning",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "loipersbach",
        "hzbnr": 208785,
        "name": "Loipersbach",
        "water": "Schwarza",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "aspang_holl",
        "hzbnr": 208819,
        "name": "Aspang-Höll",
        "water": "Großer Pestingbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bad_erlach",
        "hzbnr": 208843,
        "name": "Bad Erlach",
        "water": "Pitten",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "erlaufboden_evn",
        "hzbnr": 208850,
        "name": "Erlaufboden (EVN)",
        "water": "Große Erlauf",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "deutsch_haslau",
        "hzbnr": 209007,
        "name": "Deutsch Haslau",
        "water": "Leitha",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "niederabsdorf",
        "hzbnr": 209189,
        "name": "Niederabsdorf",
        "water": "Zaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "zillingdorf",
        "hzbnr": 209288,
        "name": "Zillingdorf",
        "water": "Leitha",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "frauenhofen",
        "hzbnr": 209338,
        "name": "Frauenhofen",
        "water": "Taffa",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "asparn_an_der_zaya",
        "hzbnr": 209452,
        "name": "Asparn an der Zaya",
        "water": "Zaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "klausenleopoldsdorf",
        "hzbnr": 209478,
        "name": "Klausenleopoldsdorf",
        "water": "Schwechat",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "boheimkirchen",
        "hzbnr": 209486,
        "name": "Böheimkirchen",
        "water": "Perschling",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "pulkau",
        "hzbnr": 209510,
        "name": "Pulkau",
        "water": "Pulkau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lunz_am_see_seestrasse",
        "hzbnr": 209551,
        "name": "Lunz am See (Seestrasse)",
        "water": "Ois",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "eggenburg_klaranlage",
        "hzbnr": 209643,
        "name": "Eggenburg (Kläranlage)",
        "water": "Schmida",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "traiskirchen",
        "hzbnr": 209718,
        "name": "Traiskirchen",
        "water": "Schwechat",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kirchschlag_in_der_buckl_welt",
        "hzbnr": 210302,
        "name": "Kirchschlag in der Buckl.Welt",
        "water": "Zöbernbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rosenburg",
        "hzbnr": 208520,
        "name": "Rosenburg",
        "water": "Taffa",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wolkersdorf",
        "hzbnr": 208769,
        "name": "Wolkersdorf",
        "water": "Russbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "herzogenburg",
        "hzbnr": 208777,
        "name": "Herzogenburg",
        "water": "Traisen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "ramsau",
        "hzbnr": 208793,
        "name": "Ramsau",
        "water": "Ramsaubach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hohenberg_sud",
        "hzbnr": 208868,
        "name": "Hohenberg (Süd)",
        "water": "Traisen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "ybbsitz_obergurhof",
        "hzbnr": 209130,
        "name": "Ybbsitz (Obergurhof)",
        "water": "Kleine Ybbs",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "deutsch_brodersdorf_messseilbahn",
        "hzbnr": 214031,
        "name": "Deutsch Brodersdorf (Messseilbahn)",
        "water": "Leitha",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "haugsdorf",
        "hzbnr": 209155,
        "name": "Haugsdorf",
        "water": "Pulkau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wang",
        "hzbnr": 209817,
        "name": "Wang",
        "water": "Kleine Erlauf",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "scheibbs",
        "hzbnr": 209882,
        "name": "Scheibbs",
        "water": "Große Erlauf",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gostling",
        "hzbnr": 214254,
        "name": "Göstling",
        "water": "Ybbs",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "altmanns_brucke",
        "hzbnr": 214296,
        "name": "Altmanns (Brücke)",
        "water": "Braunaubach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "loich",
        "hzbnr": 214312,
        "name": "Loich",
        "water": "Pielach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wiener_neustadt_lichtenwortherg",
        "hzbnr": 214387,
        "name": "Wiener Neustadt (Lichtenwörtherg.)",
        "water": "Warme Fischa",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "petersbaumgarten",
        "hzbnr": 214395,
        "name": "Petersbaumgarten",
        "water": "Pitten",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_martin_brucke_polzl",
        "hzbnr": 214429,
        "name": "St. Martin (Brücke Pölzl)",
        "water": "Lainsitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "dobersberg_b30",
        "hzbnr": 214460,
        "name": "Dobersberg (B30)",
        "water": "Deutsche Thaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "ebreichsdorf_steg",
        "hzbnr": 214502,
        "name": "Ebreichsdorf (Steg)",
        "water": "Piesting",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gotzendorf",
        "hzbnr": 215517,
        "name": "Götzendorf",
        "water": "Leitha",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rainfeld",
        "hzbnr": 215574,
        "name": "Rainfeld",
        "water": "Gölsen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "turnitz_waldsiedlung",
        "hzbnr": 215640,
        "name": "Türnitz (Waldsiedlung)",
        "water": "Traisen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "jahrsdorf",
        "hzbnr": 204677,
        "name": "Jahrsdorf",
        "water": "Mattig",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mamling",
        "hzbnr": 204719,
        "name": "Mamling",
        "water": "Mühlheimer Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "haging",
        "hzbnr": 204750,
        "name": "Haging",
        "water": "Antiesen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "riedau",
        "hzbnr": 204784,
        "name": "Riedau",
        "water": "Pram",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "alfersham",
        "hzbnr": 204834,
        "name": "Alfersham",
        "water": "Pfudabach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "pramerdorf",
        "hzbnr": 204867,
        "name": "Pramerdorf",
        "water": "Pram",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "teufelmuhle",
        "hzbnr": 204933,
        "name": "Teufelmühle",
        "water": "Große Mühl",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "still",
        "hzbnr": 204990,
        "name": "Still",
        "water": "Stillbach",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "grieskirchen",
        "hzbnr": 205013,
        "name": "Grieskirchen",
        "water": "Trattnach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bad_ischl_giselabrucke",
        "hzbnr": 205187,
        "name": "Bad Ischl (Giselabrücke)",
        "water": "Ischl",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "stauf",
        "hzbnr": 205377,
        "name": "Stauf",
        "water": "Vöckla",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "vocklabruck",
        "hzbnr": 205419,
        "name": "Vöcklabruck",
        "water": "Vöckla",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "fischerau",
        "hzbnr": 205450,
        "name": "Fischerau",
        "water": "Ager",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "penningersteg",
        "hzbnr": 205518,
        "name": "Penningersteg",
        "water": "Alm",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kirchdorf",
        "hzbnr": 205633,
        "name": "Kirchdorf",
        "water": "Krems",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kremsmunster",
        "hzbnr": 205641,
        "name": "Kremsmünster",
        "water": "Krems",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kremsdorf",
        "hzbnr": 205658,
        "name": "Kremsdorf",
        "water": "Krems",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "reichraming",
        "hzbnr": 205740,
        "name": "Reichraming",
        "water": "Reichramingbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "jagerberg",
        "hzbnr": 205757,
        "name": "Jägerberg",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kniewas",
        "hzbnr": 205799,
        "name": "Kniewas",
        "water": "Steyr",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "st_pankraz",
        "hzbnr": 205831,
        "name": "St. Pankraz",
        "water": "Teichl",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "steyrling",
        "hzbnr": 205856,
        "name": "Steyrling",
        "water": "Steyrling",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "klaus_an_der_pyhrnbahn",
        "hzbnr": 205864,
        "name": "Klaus an der Pyhrnbahn",
        "water": "Steyr",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "molln",
        "hzbnr": 205898,
        "name": "Molln",
        "water": "Krumme Steyrling",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "pergern",
        "hzbnr": 205914,
        "name": "Pergern",
        "water": "Steyr",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "steyr_ortskai",
        "hzbnr": 205922,
        "name": "Steyr (Ortskai)",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "konigswiesen",
        "hzbnr": 205997,
        "name": "Königswiesen",
        "water": "Große Naarn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "haid",
        "hzbnr": 206029,
        "name": "Haid",
        "water": "Naarn",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "theresienthal_gmunden",
        "hzbnr": 206128,
        "name": "Theresienthal (Gmunden)",
        "water": "Traun",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "niederspaching",
        "hzbnr": 206169,
        "name": "Niederspaching",
        "water": "Aschach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "scharding_schreibpegel",
        "hzbnr": 206201,
        "name": "Schärding (Schreibpegel)",
        "water": "Inn",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "wels_lichtenegg",
        "hzbnr": 206391,
        "name": "Wels-Lichtenegg",
        "water": "Traun (ohne Mühlbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "leopoldschlag",
        "hzbnr": 206557,
        "name": "Leopoldschlag",
        "water": "Maltsch",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "steyr_zollamt",
        "hzbnr": 206599,
        "name": "Steyr (Zollamt)",
        "water": "Ramingbach",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "zwettl_an_der_rodl",
        "hzbnr": 206656,
        "name": "Zwettl an der Rodl",
        "water": "Große Rodl",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "weitersfelden",
        "hzbnr": 206680,
        "name": "Weitersfelden",
        "water": "Waldaist",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "unterrohr",
        "hzbnr": 206813,
        "name": "Unterrohr",
        "water": "Sulzbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wald_i_pzg",
        "hzbnr": 203026,
        "name": "Wald i. Pzg.",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mittersill",
        "hzbnr": 203075,
        "name": "Mittersill",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "zell_am_see",
        "hzbnr": 203117,
        "name": "Zell am See",
        "water": "Zeller See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "bad_hofgastein",
        "hzbnr": 203208,
        "name": "Bad Hofgastein",
        "water": "Gasteiner Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schwaighofbrucke",
        "hzbnr": 203265,
        "name": "Schwaighofbrücke",
        "water": "Lammer",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "obergau",
        "hzbnr": 203307,
        "name": "Obergäu",
        "water": "Lammer",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "golling",
        "hzbnr": 203323,
        "name": "Golling",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "viehhofen",
        "hzbnr": 203463,
        "name": "Viehhofen",
        "water": "Saalach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "weibach",
        "hzbnr": 203497,
        "name": "Weißbach",
        "water": "Saalach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "oberndorf",
        "hzbnr": 203539,
        "name": "Oberndorf",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "siezenheim",
        "hzbnr": 203570,
        "name": "Siezenheim",
        "water": "Saalach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wallersee_sp",
        "hzbnr": 203588,
        "name": "Wallersee (SP)",
        "water": "Wallersee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "mattsee",
        "hzbnr": 203604,
        "name": "Mattsee",
        "water": "Mattsee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "obertrum",
        "hzbnr": 203612,
        "name": "Obertrum",
        "water": "Obertrumer See",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "st_gilgen",
        "hzbnr": 203646,
        "name": "St. Gilgen",
        "water": "Wolfgangsee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "fuschl_am_see",
        "hzbnr": 203653,
        "name": "Fuschl am See",
        "water": "Fuschlsee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "altenmarkt_im_pongau",
        "hzbnr": 203711,
        "name": "Altenmarkt im Pongau",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "tamsweg",
        "hzbnr": 203786,
        "name": "Tamsweg",
        "water": "Taurach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mortelsdorf",
        "hzbnr": 203794,
        "name": "Mörtelsdorf",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wallnerau",
        "hzbnr": 203901,
        "name": "Wallnerau",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kendlbruck",
        "hzbnr": 203976,
        "name": "Kendlbruck",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "werfen",
        "hzbnr": 204032,
        "name": "Werfen",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "salzburg_nonntal",
        "hzbnr": 204180,
        "name": "Salzburg-Nonntal",
        "water": "Salzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schladming",
        "hzbnr": 210641,
        "name": "Schladming",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "trautenfels",
        "hzbnr": 210740,
        "name": "Trautenfels",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "liezen_rothelbrucke",
        "hzbnr": 210799,
        "name": "Liezen (Röthelbrücke)",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "admont",
        "hzbnr": 210823,
        "name": "Admont",
        "water": "Enns",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "feldbach",
        "hzbnr": 210989,
        "name": "Feldbach",
        "water": "Raab",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rohrbach",
        "hzbnr": 210997,
        "name": "Rohrbach",
        "water": "Lafnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "waltersdorf",
        "hzbnr": 211011,
        "name": "Waltersdorf",
        "water": "Safen",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "anger",
        "hzbnr": 211029,
        "name": "Anger",
        "water": "Feistritz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gestuthof",
        "hzbnr": 211086,
        "name": "Gestüthof",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_georgen",
        "hzbnr": 211102,
        "name": "St. Georgen",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "zeltweg",
        "hzbnr": 211136,
        "name": "Zeltweg",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "neuberg",
        "hzbnr": 211227,
        "name": "Neuberg",
        "water": "Mürz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kindthal",
        "hzbnr": 211243,
        "name": "Kindthal",
        "water": "Mürz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bruck",
        "hzbnr": 211292,
        "name": "Bruck",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "graz_ohne_muhlkanal",
        "hzbnr": 211326,
        "name": "Graz (ohne Mühlkanal)",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "voitsberg",
        "hzbnr": 211334,
        "name": "Voitsberg",
        "water": "Kainach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lieboch",
        "hzbnr": 211342,
        "name": "Lieboch",
        "water": "Kainach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schwanberg",
        "hzbnr": 211383,
        "name": "Schwanberg",
        "water": "Schwarze Sulm",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "leibnitz",
        "hzbnr": 211458,
        "name": "Leibnitz",
        "water": "Sulm",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mureck_ohne_ausleitung",
        "hzbnr": 211490,
        "name": "Mureck (ohne Ausleitung)",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gundorf",
        "hzbnr": 211656,
        "name": "Gündorf",
        "water": "Saggau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "frauental",
        "hzbnr": 211664,
        "name": "Frauental",
        "water": "Lassnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_ruprecht",
        "hzbnr": 211706,
        "name": "St. Ruprecht",
        "water": "Raab",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mellach_ohne_muhlkanal",
        "hzbnr": 211847,
        "name": "Mellach (ohne Mühlkanal)",
        "water": "Mur",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hormsdorf",
        "hzbnr": 211961,
        "name": "Hörmsdorf",
        "water": "Saggau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lechaschau",
        "hzbnr": 201087,
        "name": "Lechaschau",
        "water": "Lech",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "scharnitz_weidach",
        "hzbnr": 201095,
        "name": "Scharnitz (Weidach)",
        "water": "Isar",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "vils_lande",
        "hzbnr": 201111,
        "name": "Vils (Lände)",
        "water": "Vils",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kajetansbrucke",
        "hzbnr": 201178,
        "name": "Kajetansbrücke",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "prutz",
        "hzbnr": 201194,
        "name": "Prutz",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "perjen",
        "hzbnr": 201293,
        "name": "Perjen",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "vent_oberh_niedertalbach",
        "hzbnr": 201350,
        "name": "Vent (oberh. Niedertalbach)",
        "water": "Rofenache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "huben",
        "hzbnr": 201392,
        "name": "Huben",
        "water": "Ötztaler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "tumpen",
        "hzbnr": 201434,
        "name": "Tumpen",
        "water": "Ötztaler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "magerbach",
        "hzbnr": 201459,
        "name": "Magerbach",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "innsbruck_oberh_sill",
        "hzbnr": 201525,
        "name": "Innsbruck (oberh. Sill)",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "puig",
        "hzbnr": 201574,
        "name": "Puig",
        "water": "Sill",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "innsbruck_reichenau",
        "hzbnr": 201624,
        "name": "Innsbruck-Reichenau",
        "water": "Sill",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "jenbach_rotholz",
        "hzbnr": 201681,
        "name": "Jenbach-Rotholz",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mayrhofen",
        "hzbnr": 201749,
        "name": "Mayrhofen",
        "water": "Ziller",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "zell",
        "hzbnr": 201756,
        "name": "Zell",
        "water": "Ziller",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rohr",
        "hzbnr": 201772,
        "name": "Rohr",
        "water": "Gerlosbach",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "hart_im_zillertal",
        "hzbnr": 201780,
        "name": "Hart im Zillertal",
        "water": "Ziller",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "brixlegg",
        "hzbnr": 201806,
        "name": "Brixlegg",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mariathal",
        "hzbnr": 201822,
        "name": "Mariathal",
        "water": "Brandenberger Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "horbrunn",
        "hzbnr": 201848,
        "name": "Hörbrunn",
        "water": "Kelchsauer Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bruckhausl",
        "hzbnr": 201863,
        "name": "Bruckhäusl",
        "water": "Brixentaler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kirchbichl",
        "hzbnr": 201889,
        "name": "Kirchbichl",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kitzbuhel_bahnhofsbrucke",
        "hzbnr": 201913,
        "name": "Kitzbühel (Bahnhofsbrücke)",
        "water": "Kitzbüheler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "sperten",
        "hzbnr": 201921,
        "name": "Sperten",
        "water": "Aschauer Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_johann_in_tirol",
        "hzbnr": 201939,
        "name": "St. Johann in Tirol",
        "water": "Kitzbüheler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "landeck_bruggen",
        "hzbnr": 202036,
        "name": "Landeck-Bruggen",
        "water": "Sanna",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "klamm",
        "hzbnr": 202127,
        "name": "Klamm",
        "water": "Leutascher Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "krossbach",
        "hzbnr": 202283,
        "name": "Krössbach",
        "water": "Ruetz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kossen_hutte",
        "hzbnr": 202382,
        "name": "Kössen-Hütte",
        "water": "Großache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "rabland",
        "hzbnr": 212027,
        "name": "Rabland",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bruhl",
        "hzbnr": 212092,
        "name": "Brühl",
        "water": "Isel",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hopfgarten_i_def_zwenewald",
        "hzbnr": 212100,
        "name": "Hopfgarten i. Def.-Zwenewald",
        "water": "Schwarzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "telfs_fussgangersteg",
        "hzbnr": 230078,
        "name": "Telfs (Fussgängersteg)",
        "water": "Inn",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "in_der_au",
        "hzbnr": 230706,
        "name": "In der Au",
        "water": "Melach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lienz_falkensteinsteg",
        "hzbnr": 231092,
        "name": "Lienz-Falkensteinsteg",
        "water": "Drau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "going_am_wilden_kaiser",
        "hzbnr": 202614,
        "name": "Going am Wilden Kaiser",
        "water": "Goinger Bach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kirchberg_i_t",
        "hzbnr": 202622,
        "name": "Kirchberg i. T.",
        "water": "Aschauer Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kossen_waidach",
        "hzbnr": 202630,
        "name": "Kössen-Waidach",
        "water": "Kohlenbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bangs",
        "hzbnr": 200014,
        "name": "Bangs",
        "water": "Rhein",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schruns",
        "hzbnr": 200048,
        "name": "Schruns",
        "water": "Litz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "garsella",
        "hzbnr": 200105,
        "name": "Garsella",
        "water": "Lutz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gisingen",
        "hzbnr": 200147,
        "name": "Gisingen",
        "water": "Ill",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "laterns",
        "hzbnr": 200154,
        "name": "Laterns",
        "water": "Frutz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lustenau_hochster_brucke",
        "hzbnr": 200196,
        "name": "Lustenau (Höchster Brücke)",
        "water": "Rhein",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "enz",
        "hzbnr": 200204,
        "name": "Enz",
        "water": "Dornbirnerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hoher_steg",
        "hzbnr": 200212,
        "name": "Hoher Steg",
        "water": "Dornbirnerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lustenau_hofsteig",
        "hzbnr": 200220,
        "name": "Lustenau (Hofsteig)",
        "water": "Rheintalbinnenkanal",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hopfreben",
        "hzbnr": 200246,
        "name": "Hopfreben",
        "water": "Bregenzerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "au",
        "hzbnr": 200253,
        "name": "Au",
        "water": "Bregenzerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mellau",
        "hzbnr": 200261,
        "name": "Mellau",
        "water": "Bregenzerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schonenbach_hengstig",
        "hzbnr": 200287,
        "name": "Schönenbach (Hengstig)",
        "water": "Subersach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "thal_martinsbrucke",
        "hzbnr": 200311,
        "name": "Thal (Martinsbrücke)",
        "water": "Rotach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kennelbach",
        "hzbnr": 200329,
        "name": "Kennelbach",
        "water": "Bregenzerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lochau",
        "hzbnr": 200345,
        "name": "Lochau",
        "water": "Ruggbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "unterhochsteg",
        "hzbnr": 200352,
        "name": "Unterhochsteg",
        "water": "Leiblach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lech_tannbergbrucke",
        "hzbnr": 200378,
        "name": "Lech (Tannbergbrücke)",
        "water": "Lech",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lauterach",
        "hzbnr": 200410,
        "name": "Lauterach",
        "water": "Dornbirnerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schwarzach",
        "hzbnr": 200428,
        "name": "Schwarzach",
        "water": "Schwarzach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "reuthe",
        "hzbnr": 200493,
        "name": "Reuthe",
        "water": "Bizauerbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bozenau",
        "hzbnr": 231795,
        "name": "Bozenau",
        "water": "Bregenzerach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kalberweide",
        "hzbnr": 200584,
        "name": "Kälberweide",
        "water": "Leckenbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hohenems",
        "hzbnr": 200576,
        "name": "Hohenems",
        "water": "Emsbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hittisau_vkw",
        "hzbnr": 200451,
        "name": "Hittisau (VKW)",
        "water": "Bolgenach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "klosterle_obb",
        "hzbnr": 200592,
        "name": "Klösterle (ÖBB)",
        "water": "Alfenz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "sulz",
        "hzbnr": 200642,
        "name": "Sulz",
        "water": "Frutz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hard_muhlestrasse",
        "hzbnr": 200675,
        "name": "Hard (Mühlestrasse)",
        "water": "Lauterachbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "ybbs",
        "hzbnr": 207126,
        "name": "Ybbs",
        "water": "Donau",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "bernhardsthal_staatsgrenzpunkt",
        "hzbnr": 207290,
        "name": "Bernhardsthal (Staatsgrenzpunkt)",
        "water": "Thaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hohenau_an_der_march_fluss_km",
        "hzbnr": 207308,
        "name": "Hohenau an der March (Fluss-km)",
        "water": "March",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "angern_an_der_march",
        "hzbnr": 207324,
        "name": "Angern an der March",
        "water": "March",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kienstock",
        "hzbnr": 207357,
        "name": "Kienstock",
        "water": "Donau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "mauthausen",
        "hzbnr": 207084,
        "name": "Mauthausen",
        "water": "Donau",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "mannersdorf_an_der_rabnitz",
        "hzbnr": 210054,
        "name": "Mannersdorf an der Rabnitz",
        "water": "Rabnitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "linz",
        "hzbnr": 207068,
        "name": "Linz",
        "water": "Donau",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "achleiten",
        "hzbnr": 207019,
        "name": "Achleiten",
        "water": "Donau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "korneuburg",
        "hzbnr": 207241,
        "name": "Korneuburg",
        "water": "Donau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "wildungsmauer",
        "hzbnr": 207373,
        "name": "Wildungsmauer",
        "water": "Donau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "thebnerstral",
        "hzbnr": 207407,
        "name": "Thebnerstraßl",
        "water": "Donau",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_georgen_am_langsee",
        "hzbnr": 213801,
        "name": "St. Georgen am Längsee",
        "water": "Längsee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "winklern",
        "hzbnr": 212373,
        "name": "Winklern",
        "water": "Möll",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "lohstampf",
        "hzbnr": 206268,
        "name": "Lohstampf",
        "water": "Messenbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "grabensee",
        "hzbnr": 204131,
        "name": "Grabensee",
        "water": "Grabensee",
        "parameter": "W",
        "unit": "cm",
    },
    {
        "suffix": "lienz",
        "hzbnr": 212167,
        "name": "Lienz",
        "water": "Isel",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bregenz_seepegel",
        "hzbnr": 200337,
        "name": "Bregenz (Seepegel)",
        "water": "Bodensee",
        "parameter": "W",
        "unit": "m ü.A",
    },
    {
        "suffix": "steeg",
        "hzbnr": 201012,
        "name": "Steeg",
        "water": "Lech",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "ehrendorf",
        "hzbnr": 208462,
        "name": "Ehrendorf",
        "water": "Lainsitz",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hoheneich",
        "hzbnr": 208579,
        "name": "Hoheneich",
        "water": "Braunaubach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "schwarzenau_sud",
        "hzbnr": 208611,
        "name": "Schwarzenau (Süd)",
        "water": "Deutsche Thaya",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "st_lorenz",
        "hzbnr": 205294,
        "name": "St. Lorenz",
        "water": "Griesler Ache",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "hinterbichl",
        "hzbnr": 212043,
        "name": "Hinterbichl",
        "water": "Isel",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "gussing",
        "hzbnr": 210286,
        "name": "Güssing",
        "water": "Strem",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "fraham",
        "hzbnr": 205039,
        "name": "Fraham",
        "water": "Innbach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "neumarkt_im_hausruckkreis",
        "hzbnr": 205047,
        "name": "Neumarkt im Hausruckkreis",
        "water": "Dürre Aschach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "kropfmuhle",
        "hzbnr": 205054,
        "name": "Kropfmühle",
        "water": "Aschach",
        "parameter": "Q",
        "unit": "m³/s",
    },
    {
        "suffix": "bad_ischl_maxquelle",
        "hzbnr": 205153,
        "name": "Bad Ischl (Maxquelle)",
        "water": "Traun",
        "parameter": "Q",
        "unit": "m³/s",
    },
]

GROUNDWATER_STATIONS: list[dict[str, int | str]] = [
    {"suffix": "st_johann_i_t_bl_19", "hzbnr": 353904, "name": "St.Johann i.T., Bl 19"},
    {"suffix": "straen_bl_0003", "hzbnr": 353342, "name": "Straßen, Bl   0003"},
    {"suffix": "st_polten_bl_251", "hzbnr": 322891, "name": "St.Pölten, Bl 251"},
    {"suffix": "vorderberg_bl_118", "hzbnr": 338343, "name": "Vorderberg, Bl 118"},
    {"suffix": "pottelsdorf_bl_43", "hzbnr": 353573, "name": "Pöttelsdorf, Bl 43"},
    {
        "suffix": "neustift_a_d_lafnitz_bl_30",
        "hzbnr": 345710,
        "name": "Neustift a.d. Lafnitz, Bl 30",
    },
    {"suffix": "neckenmarkt_bl_7", "hzbnr": 345702, "name": "Neckenmarkt, Bl 7"},
    {"suffix": "illmitz_bl_159", "hzbnr": 345629, "name": "Illmitz, Bl 159"},
    {
        "suffix": "deutsch_jahrndorf_bl_34",
        "hzbnr": 345595,
        "name": "Deutsch Jahrndorf, Bl 34",
    },
    {
        "suffix": "markt_st_martin_bl_1",
        "hzbnr": 345520,
        "name": "Markt St. Martin, Bl 1",
    },
    {"suffix": "halbturn_bl_151", "hzbnr": 345298, "name": "Halbturn, Bl 151"},
    {"suffix": "andau_bl_150", "hzbnr": 345280, "name": "Andau, Bl 150"},
    {
        "suffix": "klostermarienberg_bl_16",
        "hzbnr": 335810,
        "name": "Klostermarienberg, Bl 16",
    },
    {"suffix": "nickelsdorf_bl_52a", "hzbnr": 335547, "name": "Nickelsdorf, Bl 52A"},
    {
        "suffix": "deutsch_kaltenbrunn_bl_12",
        "hzbnr": 335315,
        "name": "Deutsch Kaltenbrunn, Bl 12",
    },
    {"suffix": "gols_bl_125", "hzbnr": 319418, "name": "Gols, Bl 125"},
    {
        "suffix": "neusiedl_am_see_bl_124",
        "hzbnr": 316174,
        "name": "Neusiedl am See, Bl 124",
    },
    {"suffix": "gols_bl_39", "hzbnr": 316166, "name": "Gols, Bl 39"},
    {"suffix": "kittsee_br_17", "hzbnr": 316091, "name": "Kittsee, Br 17"},
    {"suffix": "pfunds_bl12_s2", "hzbnr": 358440, "name": "Pfunds, Bl12 (S2)"},
    {"suffix": "oetting_bl_424", "hzbnr": 338780, "name": "Oetting, Bl 424"},
    {"suffix": "mauthen_bl_701", "hzbnr": 338327, "name": "Mauthen, Bl 701"},
    {"suffix": "moos_bl_328", "hzbnr": 338087, "name": "Moos, Bl 328"},
    {"suffix": "eberndorf_bl_327", "hzbnr": 338061, "name": "Eberndorf, Bl 327"},
    {"suffix": "muschk_bl_205", "hzbnr": 338855, "name": "Muschk, Bl 205"},
    {"suffix": "maria_saal_bl_219", "hzbnr": 338632, "name": "Maria Saal, Bl 219"},
    {
        "suffix": "feistritz_i_r_bl_510",
        "hzbnr": 338236,
        "name": "Feistritz i.R., Bl 510",
    },
    {"suffix": "klagenfurt_bl_204", "hzbnr": 318089, "name": "Klagenfurt, Bl 204"},
    {
        "suffix": "kleblach_lind_bl_403",
        "hzbnr": 317883,
        "name": "Kleblach-Lind, Bl 403",
    },
    {"suffix": "judendorf_bl_14_a", "hzbnr": 309674, "name": "Judendorf, Bl  14 A"},
    {"suffix": "burg_bl_3", "hzbnr": 353631, "name": "Burg Bl 3"},
    {"suffix": "lockenhaus_bl_2", "hzbnr": 353524, "name": "Lockenhaus, Bl 2"},
    {
        "suffix": "neufeld_a_d_leitha_bl_10",
        "hzbnr": 345868,
        "name": "Neufeld a.d. Leitha, Bl 10",
    },
    {"suffix": "neumarkt_a_d_r_bl_7", "hzbnr": 345728, "name": "Neumarkt a.d.R., Bl 7"},
    {"suffix": "parndorf_bl_59", "hzbnr": 345181, "name": "Parndorf, Bl 59"},
    {"suffix": "pama_bl_6", "hzbnr": 306274, "name": "Pama, Bl 6"},
    {
        "suffix": "ried_im_zillertal_bl_1",
        "hzbnr": 358093,
        "name": "Ried im Zillertal, Bl 1",
    },
    {"suffix": "gro_enzersdorf_br", "hzbnr": 304733, "name": "Groß-Enzersdorf, Br"},
    {"suffix": "deutsch_wagram_bl", "hzbnr": 304584, "name": "Deutsch Wagram, Bl"},
    {"suffix": "judenau_br", "hzbnr": 304014, "name": "Judenau, Br"},
    {"suffix": "kollersdorf_bl", "hzbnr": 303198, "name": "Kollersdorf, Bl"},
    {"suffix": "donaudorf_br", "hzbnr": 303081, "name": "Donaudorf, Br"},
    {"suffix": "reisenberg_bl_29", "hzbnr": 301242, "name": "Reisenberg, Bl 29"},
    {"suffix": "leobersdorf_bl_451", "hzbnr": 300699, "name": "Leobersdorf, Bl 451"},
    {"suffix": "achau_br", "hzbnr": 300012, "name": "Achau, Br"},
    {"suffix": "ferlach_bl_518", "hzbnr": 354688, "name": "Ferlach, Bl 518"},
    {"suffix": "penk_bl_633", "hzbnr": 354563, "name": "Penk, Bl 633"},
    {"suffix": "friesach_bl_893", "hzbnr": 351890, "name": "Friesach, Bl 893"},
    {"suffix": "kamering_bl_623", "hzbnr": 338988, "name": "Kamering, Bl 623"},
    {
        "suffix": "schutzen_am_gebirge_bl_ii",
        "hzbnr": 313304,
        "name": "Schützen am Gebirge, Bl  II",
    },
    {"suffix": "leobendorf_bl_351", "hzbnr": 331272, "name": "Leobendorf, Bl 351"},
    {
        "suffix": "niederabsdorf_bl_328",
        "hzbnr": 327312,
        "name": "Niederabsdorf, Bl 328",
    },
    {
        "suffix": "obergrafendorf_bl_315",
        "hzbnr": 327171,
        "name": "Obergrafendorf, Bl 315",
    },
    {
        "suffix": "bernhardsthal_bl_266",
        "hzbnr": 326637,
        "name": "Bernhardsthal, Bl 266",
    },
    {
        "suffix": "kottingburgstall_bl_259",
        "hzbnr": 326512,
        "name": "Kottingburgstall, Bl 259",
    },
    {"suffix": "ornding_bl_2043_004", "hzbnr": 322800, "name": "Ornding, Bl 2043.004"},
    {"suffix": "absdorf_bl_214", "hzbnr": 319228, "name": "Absdorf, Bl 214"},
    {
        "suffix": "langenzersdorf_br_2112",
        "hzbnr": 313221,
        "name": "Langenzersdorf, Br 2112",
    },
    {
        "suffix": "marchegg_eisenbahnstation_br",
        "hzbnr": 304915,
        "name": "Marchegg-Eisenbahnstation, Br",
    },
    {"suffix": "kopfstetten_br", "hzbnr": 304790, "name": "Kopfstetten, Br"},
    {"suffix": "st_andra_bl_901", "hzbnr": 338525, "name": "St. Andrä, Bl 901"},
    {
        "suffix": "st_andra_am_zicksee_br_107",
        "hzbnr": 306043,
        "name": "St. Andrä am Zicksee, Br 107",
    },
    {
        "suffix": "thuringen_bl_05_41_01_a",
        "hzbnr": 309344,
        "name": "Thüringen, Bl 05.41.01 A",
    },
    {
        "suffix": "tannheim_innerg_bl_1",
        "hzbnr": 342659,
        "name": "Tannheim-Innerg., Bl 1",
    },
    {
        "suffix": "umhausen_tumpen_bl_2_kbt1",
        "hzbnr": 346239,
        "name": "Umhausen-Tumpen, Bl 2 (KBT1)",
    },
    {"suffix": "kleinschonau_bl_466", "hzbnr": 337469, "name": "Kleinschönau, Bl 466"},
    {"suffix": "krollendorf_bl_456", "hzbnr": 337378, "name": "Kröllendorf, Bl 456"},
    {"suffix": "pillichsdorf_bl_452", "hzbnr": 337337, "name": "Pillichsdorf, Bl 452"},
    {"suffix": "poggstall_bl_442", "hzbnr": 337212, "name": "Pöggstall, Bl 442"},
    {
        "suffix": "st_peter_in_der_au_bl_438",
        "hzbnr": 337170,
        "name": "St.Peter in der Au, Bl 438",
    },
    {"suffix": "hagsdorf_blt_427", "hzbnr": 337063, "name": "Hagsdorf, Blt 427"},
    {
        "suffix": "enzersdorf_im_thale_bl_419",
        "hzbnr": 331991,
        "name": "Enzersdorf im Thale, Bl 419",
    },
    {"suffix": "durnrohr_blt_409", "hzbnr": 331892, "name": "Dürnrohr, Blt 409"},
    {"suffix": "mold_bl_401", "hzbnr": 331819, "name": "Mold, Bl 401"},
    {
        "suffix": "klausen_leopoldsdorf_bl_365",
        "hzbnr": 331504,
        "name": "Klausen-Leopoldsdorf, Bl 365",
    },
    {"suffix": "breitensee_bl_359", "hzbnr": 331447, "name": "Breitensee, Bl 359"},
    {"suffix": "st_valentin_bl_316", "hzbnr": 327189, "name": "St.Valentin, Bl 316"},
    {"suffix": "wappeltsham_br_1_2", "hzbnr": 359471, "name": "Wappeltsham, Br 1.2"},
    {"suffix": "freistadt_br_8_2", "hzbnr": 324921, "name": "Freistadt, Br 8.2"},
    {
        "suffix": "obermicheldorf_br_5_4",
        "hzbnr": 324913,
        "name": "Obermicheldorf, Br 5.4",
    },
    {"suffix": "gampern_br_10_2", "hzbnr": 324848, "name": "Gampern, Br 10.2"},
    {"suffix": "lungendorf_br_64_2", "hzbnr": 324772, "name": "Lungendorf, Br 64.2"},
    {"suffix": "ried_i_trk_br_33_2", "hzbnr": 324707, "name": "Ried I.Trk., Br 33.2"},
    {"suffix": "st_peter_br_2_2", "hzbnr": 324491, "name": "St.Peter, Br 2.2"},
    {"suffix": "lengau_bl_36_4", "hzbnr": 324483, "name": "Lengau, Bl 36.4"},
    {"suffix": "posch_bl_2122_10", "hzbnr": 323568, "name": "Posch, Bl 2122.10"},
    {"suffix": "lichtenegg_br_35_1", "hzbnr": 314294, "name": "Lichtenegg, Br 35.1"},
    {
        "suffix": "hofstetten_bl_2092_015",
        "hzbnr": 308502,
        "name": "Hofstetten, Bl 2092.015",
    },
    {"suffix": "marchtrenk_br_21_9", "hzbnr": 307777, "name": "Marchtrenk, Br 21.9"},
    {"suffix": "stra_blt_2152_004", "hzbnr": 307371, "name": "Straß, Blt 2152.004"},
    {
        "suffix": "oberzogersdorf_bl_1955_011",
        "hzbnr": 359844,
        "name": "Oberzögersdorf, Bl 1955.011",
    },
    {
        "suffix": "laa_an_der_thaya_bl_463",
        "hzbnr": 337436,
        "name": "Laa an der Thaya, Bl 463",
    },
    {"suffix": "pranzing_br_1_1", "hzbnr": 344747, "name": "Pranzing, Br 1.1"},
    {"suffix": "garsten_br_1_1", "hzbnr": 344440, "name": "Garsten, Br 1.1"},
    {"suffix": "ebensee_br_88_1", "hzbnr": 344226, "name": "Ebensee, Br 88.1"},
    {"suffix": "reichersberg_br_1_3", "hzbnr": 344192, "name": "Reichersberg, Br 1.3"},
    {"suffix": "helfenberg_br_15_2", "hzbnr": 316976, "name": "Helfenberg, Br 15.2"},
    {"suffix": "mitterberg_br_54_13", "hzbnr": 375006, "name": "Mitterberg, Br 54.13"},
    {
        "suffix": "st_leonhard_ii_br_16_8_a",
        "hzbnr": 316950,
        "name": "St.Leonhard II, Br 16.8 A",
    },
    {"suffix": "st_ulrich_br_68_2", "hzbnr": 316943, "name": "St.Ulrich, Br 68.2"},
    {"suffix": "kallham_br_49_10", "hzbnr": 324996, "name": "Kallham, Br 49.10"},
    {"suffix": "hellmonsodt_br_19_2", "hzbnr": 324947, "name": "Hellmonsödt, Br 19.2"},
    {
        "suffix": "wimpassing_schwarza_bl_406",
        "hzbnr": 331868,
        "name": "Wimpassing/Schwarza, Bl 406",
    },
    {"suffix": "wieselburg_bl_339", "hzbnr": 327437, "name": "Wieselburg, Bl 339"},
    {"suffix": "tulln_e_werk_br", "hzbnr": 304410, "name": "Tulln-E.Werk, Br"},
    {
        "suffix": "unterwaltersdorf_bl_38",
        "hzbnr": 301754,
        "name": "Unterwaltersdorf, Bl 38",
    },
    {
        "suffix": "worgl_rattenberg_bl_2",
        "hzbnr": 330621,
        "name": "Wörgl-Rattenberg, Bl  2",
    },
    {"suffix": "gschwand_bl_1", "hzbnr": 358044, "name": "Gschwand, Bl 1"},
    {
        "suffix": "golling_moartal_bl_2",
        "hzbnr": 358036,
        "name": "Golling/Moartal, Bl 2",
    },
    {
        "suffix": "enns_altenmarkt_kb04_10",
        "hzbnr": 357947,
        "name": "Enns-Altenmarkt, KB04/10",
    },
    {"suffix": "mittersill_p9_06", "hzbnr": 357921, "name": "Mittersill, P9-06"},
    {
        "suffix": "st_margarethen_i_lg_p2",
        "hzbnr": 355156,
        "name": "St.Margarethen i. Lg, P2",
    },
    {"suffix": "mortelsdorf_p10", "hzbnr": 355073, "name": "Mörtelsdorf, P10"},
    {"suffix": "elsbethen_bl_1", "hzbnr": 347799, "name": "Elsbethen, Bl 1"},
    {"suffix": "bergham_bl_1", "hzbnr": 347781, "name": "Bergham, Bl 1"},
    {"suffix": "lichtenberg_bl_5", "hzbnr": 347708, "name": "Lichtenberg, Bl 5"},
    {"suffix": "morzg_bl_364", "hzbnr": 347658, "name": "Morzg, Bl 364"},
    {"suffix": "st_georgen_bl_9", "hzbnr": 321083, "name": "St.Georgen, Bl  9"},
    {"suffix": "anthering_bl_2", "hzbnr": 320861, "name": "Anthering, Bl  2"},
    {"suffix": "taxach_bl_31", "hzbnr": 320721, "name": "Taxach, Bl  31"},
    {"suffix": "gries_br_15", "hzbnr": 320549, "name": "Gries, Br 15"},
    {"suffix": "esternberg_bl_1", "hzbnr": 359505, "name": "Esternberg, Bl 1"},
    {"suffix": "wilfersdorf_bl_414", "hzbnr": 331942, "name": "Wilfersdorf, Bl 414"},
    {"suffix": "unterrohr_bl_5928", "hzbnr": 343327, "name": "Unterrohr, Bl  5928"},
    {
        "suffix": "diepersdorf_bl_38915",
        "hzbnr": 329243,
        "name": "Diepersdorf, Bl 38915",
    },
    {"suffix": "lind_bl_2507", "hzbnr": 325746, "name": "Lind, Bl  2507"},
    {
        "suffix": "friesach_st_stefan_bl_32431",
        "hzbnr": 325589,
        "name": "Friesach-St.Stefan, Bl 32431",
    },
    {"suffix": "graz_12_bl_3343", "hzbnr": 319129, "name": "Graz 12, Bl  3343"},
    {"suffix": "brunn_bl_2647", "hzbnr": 318790, "name": "Brunn, Bl  2647"},
    {"suffix": "untergralla_bl_3810", "hzbnr": 311522, "name": "Untergralla, Bl  3810"},
    {
        "suffix": "strawalchen_markt_kb1_21",
        "hzbnr": 362236,
        "name": "Straßwalchen Markt, KB1/21",
    },
    {"suffix": "hundsdorf_gw_25", "hzbnr": 361469, "name": "Hundsdorf, GW 25"},
    {"suffix": "plainfeld_hof_bl_1", "hzbnr": 361410, "name": "Plainfeld / Hof, Bl 1"},
    {"suffix": "reindorf_s_407", "hzbnr": 361386, "name": "Reindorf, S 407"},
    {"suffix": "urreiting_p_122", "hzbnr": 361360, "name": "Urreiting, P 122"},
    {"suffix": "tulbing_bl_231", "hzbnr": 319392, "name": "Tulbing, Bl 231"},
    {"suffix": "unterkarla_bl_3978", "hzbnr": 353185, "name": "Unterkarla, Bl  3978"},
    {"suffix": "frojach_bl_2191", "hzbnr": 343715, "name": "Frojach, Bl  2191"},
    {"suffix": "predlitz_bl_2001", "hzbnr": 343681, "name": "Predlitz, Bl  2001"},
    {"suffix": "johnsdorf_bl_5251", "hzbnr": 343608, "name": "Johnsdorf, Bl  5251"},
    {"suffix": "pirching_bl_5149", "hzbnr": 343566, "name": "Pirching, Bl  5149"},
    {
        "suffix": "reggerstatten_bl_5121",
        "hzbnr": 349472,
        "name": "Reggerstätten, Bl  5121",
    },
    {"suffix": "kaibing_bl_5616", "hzbnr": 343459, "name": "Kaibing, Bl  5616"},
    {"suffix": "kroisbach_bl_5637", "hzbnr": 343418, "name": "Kroisbach, Bl  5637"},
    {"suffix": "furstenfeld_bl_5831", "hzbnr": 343343, "name": "Fürstenfeld, Bl  5831"},
    {"suffix": "moos_bl_4313", "hzbnr": 340422, "name": "Moos, Bl  4313"},
    {
        "suffix": "neudorf_bei_mooskirchen_bl_4012",
        "hzbnr": 340042,
        "name": "Neudorf bei Mooskirchen, Bl  4012",
    },
    {"suffix": "wolfsthal_bl_350", "hzbnr": 331264, "name": "Wolfsthal, Bl  350"},
    {
        "suffix": "andelsbuch_bl_30_1_03",
        "hzbnr": 327817,
        "name": "Andelsbuch, Bl 30.1.03",
    },
    {"suffix": "saggau_bl_4363", "hzbnr": 356659, "name": "Saggau, Bl  4363"},
    {"suffix": "admont_bl_1562", "hzbnr": 356477, "name": "Admont, Bl  1562"},
    {"suffix": "grobming_bl_1141", "hzbnr": 356386, "name": "Gröbming, Bl   1141"},
    {"suffix": "muhlen_bl_6050", "hzbnr": 356295, "name": "Mühlen, Bl   6050"},
    {"suffix": "pinggau_bl_59993", "hzbnr": 356261, "name": "Pinggau, Bl 59993"},
    {
        "suffix": "fladnitz_im_raabtal_bl_5167",
        "hzbnr": 343533,
        "name": "Fladnitz im Raabtal, Bl  5167",
    },
    {"suffix": "kellerdorf_bl_3937", "hzbnr": 349282, "name": "Kellerdorf, Bl  3937"},
    {"suffix": "blumau_bl_5993", "hzbnr": 343897, "name": "Blumau, Bl  5993"},
    {"suffix": "neustift_bl_5987", "hzbnr": 343863, "name": "Neustift, Bl  5987"},
    {"suffix": "kaindorf_bl_59821", "hzbnr": 343830, "name": "Kaindorf, Bl 59821"},
    {"suffix": "westendorf_bl_2", "hzbnr": 358390, "name": "Westendorf, Bl 2"},
    {"suffix": "gussendorf_bl_4226", "hzbnr": 356907, "name": "Gussendorf, Bl  4226"},
    {"suffix": "barndorf_bl_1531", "hzbnr": 356733, "name": "Bärndorf, Bl  1531"},
    {"suffix": "langegg_bl_6211", "hzbnr": 356709, "name": "Langegg, Bl  6211"},
    {"suffix": "wagendorf_bl_5920", "hzbnr": 343301, "name": "Wagendorf, Bl  5920"},
    {"suffix": "wartberg_bl_2985", "hzbnr": 332999, "name": "Wartberg, Bl  2985"},
    {"suffix": "werfen_p_603", "hzbnr": 361311, "name": "Werfen, P 603"},
    {"suffix": "weyer_bl_kb10", "hzbnr": 345009, "name": "Weyer, Bl KB10"},
    {"suffix": "warth_bl_462", "hzbnr": 337428, "name": "Warth, Bl 462"},
    {"suffix": "wallsee_blt_432", "hzbnr": 337113, "name": "Wallsee, Blt 432"},
    {"suffix": "walpersdorf_bl_246", "hzbnr": 322842, "name": "Walpersdorf, Bl 246"},
    {
        "suffix": "weikendorf_remise_bl",
        "hzbnr": 305300,
        "name": "Weikendorf-Remise, Bl",
    },
    {
        "suffix": "wr_neustadt_heizhaus_bl",
        "hzbnr": 301929,
        "name": "Wr.Neustadt-Heizhaus, Bl",
    },
    {
        "suffix": "wallern_im_bgld_bl_161",
        "hzbnr": 345686,
        "name": "Wallern im Bgld., Bl 161",
    },
    {
        "suffix": "horbranz_bl_40_1_07_a",
        "hzbnr": 327767,
        "name": "Hörbranz, Bl 40.1.07 A",
    },
    {"suffix": "bach_schonau_bl_3", "hzbnr": 346114, "name": "Bach-Schönau, Bl 3"},
    {"suffix": "hotting_blt_27", "hzbnr": 339994, "name": "Hötting, Blt 27"},
    {"suffix": "waidring_bl_2", "hzbnr": 339945, "name": "Waidring, Bl 2"},
    {"suffix": "vils_bl_1", "hzbnr": 339606, "name": "Vils, Bl  1"},
    {"suffix": "reutte_blt_16", "hzbnr": 339432, "name": "Reutte, Blt 16"},
    {"suffix": "weienbach_bl_1", "hzbnr": 334813, "name": "Weißenbach, Bl 1"},
    {
        "suffix": "lengberg_bl_2_lavant_bl_4",
        "hzbnr": 334565,
        "name": "Lengberg, Bl 2 (Lavant, Bl 4)",
    },
    {"suffix": "vomp_blt_1", "hzbnr": 334458, "name": "Vomp, Blt 1"},
    {"suffix": "inzing_bl_2", "hzbnr": 330910, "name": "Inzing, Bl 2"},
    {"suffix": "scharnitz_bl_3", "hzbnr": 330837, "name": "Scharnitz, Bl 3"},
    {"suffix": "dolsach_bl_1", "hzbnr": 330795, "name": "Dölsach, Bl  1"},
    {"suffix": "lienz_bl_2", "hzbnr": 330670, "name": "Lienz, Bl 2"},
    {"suffix": "kossen_bl_2", "hzbnr": 330662, "name": "Kössen, Bl  2"},
    {"suffix": "munster_bl_1", "hzbnr": 330431, "name": "Münster, Bl  1"},
    {"suffix": "volders_bl_2", "hzbnr": 330274, "name": "Volders, Bl 2"},
    {"suffix": "altenmarkt_br_1792", "hzbnr": 356998, "name": "Altenmarkt, Br   1792"},
    {
        "suffix": "frastanz_bl_02_31_05",
        "hzbnr": 321315,
        "name": "Frastanz, Bl 02.31.05",
    },
    {
        "suffix": "nofels_bl_01_32_24_a",
        "hzbnr": 309542,
        "name": "Nofels, Bl 01.32.24 A",
    },
    {
        "suffix": "meiningen_bl_01_33_06",
        "hzbnr": 309526,
        "name": "Meiningen, Bl 01.33.06",
    },
    {
        "suffix": "altenstadt_bl_01_32_01_a",
        "hzbnr": 309393,
        "name": "Altenstadt, Bl 01.32.01 A",
    },
    {
        "suffix": "bregenz_bl_50_1_09_b",
        "hzbnr": 309385,
        "name": "Bregenz, Bl 50.1.09 B",
    },
    {"suffix": "heiterwang_bl_2", "hzbnr": 358275, "name": "Heiterwang, Bl 2"},
    {"suffix": "anras_bl_1", "hzbnr": 342022, "name": "Anras, Bl 1"},
    {"suffix": "matrei_i_o_bl_2", "hzbnr": 354209, "name": "Matrei i.O., Bl 2"},
    {"suffix": "ainet_blt_1", "hzbnr": 354175, "name": "Ainet, Blt 1"},
    {"suffix": "neustift_bl_1", "hzbnr": 354068, "name": "Neustift, Bl 1"},
    {"suffix": "arnbach_bl_2", "hzbnr": 342899, "name": "Arnbach, Bl  2"},
    {"suffix": "zams_blt_6", "hzbnr": 342741, "name": "Zams, Blt 6"},
    {
        "suffix": "langenfeld_oberried_bl_1",
        "hzbnr": 342618,
        "name": "Längenfeld-Oberried, Bl 1",
    },
    {"suffix": "mils_au_bl_1_122", "hzbnr": 346700, "name": "Mils-Au, Bl 1 (122)"},
    {"suffix": "zettling_br_3552", "hzbnr": 310821, "name": "Zettling, Br  3552"},
    {"suffix": "zurndorf_bl_56", "hzbnr": 335885, "name": "Zurndorf, Bl 56"},
    {
        "suffix": "altenstadt_bl_01_32_60",
        "hzbnr": 327635,
        "name": "Altenstadt, Bl 01.32.60",
    },
    {
        "suffix": "tosters_bl_01_32_53_a",
        "hzbnr": 327619,
        "name": "Tosters, Bl 01.32.53 A",
    },
    {"suffix": "bregenz_bl_50_1_12", "hzbnr": 322255, "name": "Bregenz, Bl 50.1.12"},
    {"suffix": "hard_bl_50_2_13", "hzbnr": 322131, "name": "Hard, Bl 50.2.13"},
    {
        "suffix": "lauterach_bl_50_2_10_a",
        "hzbnr": 322115,
        "name": "Lauterach, Bl 50.2.10 A",
    },
    {
        "suffix": "wolfurt_bl_50_2_05_a",
        "hzbnr": 322099,
        "name": "Wolfurt, Bl 50.2.05 A",
    },
    {
        "suffix": "nenzing_bl_04_30_16_b",
        "hzbnr": 321562,
        "name": "Nenzing, Bl 04.30.16 B",
    },
    {"suffix": "ludesch_bl_06_36_08", "hzbnr": 321521, "name": "Ludesch, Bl 06.36.08"},
    {"suffix": "achenkirch_bl10", "hzbnr": 360669, "name": "Achenkirch, Bl10"},
    {"suffix": "telfs_blt_17", "hzbnr": 359166, "name": "Telfs, Blt 17"},
    {"suffix": "galtur_bl_2", "hzbnr": 359018, "name": "Galtür, Bl 2"},
    {"suffix": "pettneu_bl_4", "hzbnr": 359026, "name": "Pettneu, Bl 4"},
    {
        "suffix": "mettersdorf_bl_39541",
        "hzbnr": 353292,
        "name": "Mettersdorf, Bl 39541",
    },
    {"suffix": "uberackern_w14", "hzbnr": 362418, "name": "Überackern, W14"},
    {
        "suffix": "mittelberg_bl_90_1_02",
        "hzbnr": 347435,
        "name": "Mittelberg, Bl 90.1.02",
    },
    {"suffix": "loruns_bl_08_27_11", "hzbnr": 347179, "name": "Lorüns, Bl 08.27.11"},
    {
        "suffix": "gaschurn_bl_22_00_05",
        "hzbnr": 332437,
        "name": "Gaschurn, Bl 22.00.05",
    },
    {"suffix": "schruns_bl_16_04_14", "hzbnr": 332387, "name": "Schruns, Bl 16.04.14"},
    {
        "suffix": "schnepfau_bl_30_3_09",
        "hzbnr": 332304,
        "name": "Schnepfau, Bl 30.3.09",
    },
    {"suffix": "stallehr_bl_60_1_01", "hzbnr": 332015, "name": "Stallehr, Bl 60.1.01"},
    {"suffix": "hochst_bl_50_2_27", "hzbnr": 328450, "name": "Höchst, Bl 50.2.27"},
    {"suffix": "dornbirn_bl_50_3_05", "hzbnr": 328179, "name": "Dornbirn, Bl 50.3.05"},
    {
        "suffix": "andelsbuch_bl_30_2_02",
        "hzbnr": 327874,
        "name": "Andelsbuch, Bl 30.2.02",
    },
]
